version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        labels:
          - "traefik.http.routers.weiersbach.entrypoints=websecure"
          - "traefik.http.routers.weiersbach.rule=Host(`weiersbach.goebel.app`)"
          - "traefik.http.routers.weiersbach.priority=0"
          - "traefik.http.routers.weiersbach.tls=true"
          - "traefik.http.routers.weiersbach.tls.certresolver=goebel.app"
