version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        labels:
          - "traefik.http.routers.coronaClient.entrypoints=websecure"
          - "traefik.http.routers.coronaClient.rule=Host(`corona.goebel.app`)"
          - "traefik.http.routers.coronaClient.priority=0"
          - "traefik.http.routers.coronaClient.tls=true"
          - "traefik.http.routers.coronaClient.tls.certresolver=goebel.app"
